### PR TITLE
Feature abstract blockchains

### PR DESCRIPTION
**Pull request by PouriaN**

### CODE REVIEW

**Comment by kochol** [comment]
@PouriaN Need to fix the conflicts

**Review by kochol — CHANGES_REQUESTED** [review]
Need to update from master

**Review by kochol — CHANGES_REQUESTED** [review]
Need to fix conflicts

**Comment by PouriaN** [comment]
https://github.com/prokey-io/prokey-webcore/pull/35
conflict fix in this new pull request

**Pull request closed without merging**
